
/* CURSORS */

CREATE OR REPLACE PROCEDURE GET_ALL_ALBUMS (S OUT SYS_REFCURSOR)
IS
BEGIN
OPEN S FOR SELECT ALBUMID, TITLE FROM ALBUM ORDER BY ALBUMID;
END;
/

SET SERVEROUTPUT ON;


DECLARE
S SYS_REFCURSOR; -- S IS OUR CURSOR
ALBUM_ID ALBUM.ALBUMID%TYPE; -- SET ALBUM_ID AS WHAT ALBUMID'S DATATYPE IS.
ALBUMNAME ALBUM.TITLE%TYPE;
BEGIN
GET_ALL_ALBUMS(S);
LOOP
FETCH S INTO ALBUM_ID, ALBUMNAME;
EXIT WHEN S%NOTFOUND; 
    --EXIT OUT OF LOOP WHEN NO MORE ROWS ARE AVAILABLE WITHIN THE CURSOR
DBMS_OUTPUT.PUT_LINE('CURRENT ID: ' ||  ALBUM_ID || '   CURRENT NAME: ' || ALBUMNAME);
 -- THE PIPES (||) ARE LIKE + SIGNS IN JAVA
 END LOOP;
 CLOSE S; -- CLOSE CURSOR
 END;
/











-- JDBC

CREATE TABLE SUPERHERO(
HEROID INTEGER PRIMARY KEY,
HERONAME VARCHAR2(30)
);

CREATE TABLE POWERS (
POWERID INT PRIMARY KEY,
POWERNAME VARCHAR2(30)
);

CREATE SEQUENCE HEROSEQ;
CREATE SEQUENCE POWSEQ;

CREATE OR REPLACE PROCEDURE INSERTSUPERHERO(NAME IN VARCHAR2)
AS
BEGIN
INSERT INTO SUPERHERO VALUES(HEROSEQ.NEXTVAL, NAME);
COMMIT;
END;
/
SELECT * FROM SUPERHERO;




